const $ = id => document.getElementById(id);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let index=0, step=0, timer=null, state={}, completed=new Set(), read=new Set();
const words=[['cat',125,107,0],['kitten',185,85,0],['dog',100,157,0],['puppy',178,156,0],['car',398,218,1],['bus',458,186,1],['bicycle',409,278,1],['invoice',394,79,2],['payment',463,59,2],['receipt',483,115,2]];
const colors=['#76a879','#6688c5','#cb935d'];
function nav(){ $('lesson-nav').innerHTML=groups.map((g,gi)=>`<div class="nav-group"><p class="nav-group-title">${g.label}</p>${lessons.map((l,i)=>l.group===gi?`<a class="nav-item ${index===i?'active':''}" ${index===i?'aria-current="page"':''} href="#${l.id}"><span class="nav-index">${String(i+1).padStart(2,'0')}</span><span>${l.name}</span>${completed.has(l.id)?'<span class="done-mark" aria-label="Completed">✓</span>':''}</a>`:'').join('')}</div>`).join('');$('progress').value=completed.size;$('progress-text').textContent=`${completed.size} / ${lessons.length}`;}
function stop(){if(timer){clearInterval(timer);timer=null;}$('play').textContent='Play animation';$('play').setAttribute('aria-pressed','false');}
function go(id){stop();index=Math.max(0,lessons.findIndex(l=>l.id===id));step=0;state={word:'cat',sentence:'money',position:50,length:16,task:true,role:false,example:false,format:false,scenario:0,choice:null,question:0,tab:'demo',failure:'none',approved:false,variant:'basic',description:'Look up invoice status by invoice ID. Read only. Use for status questions, not payments.',tested:false};const l=lessons[index];nav();$('breadcrumb').innerHTML=`${groups[l.group].name} <span>/</span> ${l.name.toUpperCase()}`;$('eyebrow').textContent=`${groups[l.group].label.toUpperCase()} · LESSON ${String(index+1).padStart(2,'0')}`;$('title').textContent=l.title;$('intro').textContent=l.intro;$('play-title').textContent=l.play;$('lesson-number').textContent=String(index+1).padStart(2,'0');$('explanation').innerHTML=l.idea.map(t=>`<p>${t}</p>`).join('');$('client').textContent=l.client;$('caveat').textContent=l.caveat;$('question').textContent=l.question;$('answers').innerHTML=l.answers.map((a,i)=>`<button class="answer" data-answer="${i}">${a}</button>`).join('');$('feedback').textContent='';$('source').href=l.source;$('source').textContent=l.sourceName;$('previous').disabled=index===0;$('complete').textContent=index===lessons.length-1?'Finish course':'Mark done & continue';$('sidebar').classList.remove('open');$('menu-button').setAttribute('aria-expanded','false');controls();render();}
function setState(key,value){stop();state[key]=value;step=0;render();}
function pills(options,key){return options.map(([value,label])=>`<button class="pill ${state[key]===value?'selected':''}" data-key="${key}" data-value="${value}" aria-pressed="${state[key]===value}">${label}</button>`).join('');}
function controls(){const id=lessons[index].id;let html='';if(id==='embeddings') html=`<label>Pick a word <select id="word-select">${words.map(w=>`<option>${w[0]}</option>`).join('')}</select></label><span class="small-note">Or click a point on the map.</span>`;if(id==='attention')html=pills([['money','Money bank'],['river','River bank']],'sentence');if(id==='context')html='<label>Fact position <input id="position" type="range" min="0" max="100" value="50"><output class="range-value" id="position-value">Middle</output></label><label>Prompt size <select id="length"><option value="8">Short</option><option value="16" selected>Long</option><option value="24">Very long</option></select></label>';if(id==='training')html='<span class="small-note">Play, or use Next step to see each kind of training.</span>';if(id==='prompting')html=`<div class="prompt-controls controls full-width">${[['task','Clear task'],['role','Role'],['example','Example'],['format','JSON format']].map(([k,n])=>`<label><input type="checkbox" data-prompt="${k}" ${state[k]?'checked':''}> ${n}</label>`).join('')}</div>`;if(id==='rag'||id==='rag-lab')html=`${id==='rag-lab'?pills([['demo','Try the demo'],['build','Build it']],'tab'):''}<label class="full-width">Question <select id="rag-question"><option value="0">How many leave days do I get?</option><option value="1">What is the meal limit?</option><option value="2">When does the office open?</option><option value="3">What is the CEO’s favorite color?</option></select></label>`;if(id==='approach')html='<label>Client problem <select id="scenario"><option value="0">A shorter answer</option><option value="1">Changing company rules</option><option value="2">A repeated writing style</option></select></label>';if(id==='tools')html='<span class="small-note">Request: “Where is order A12?”</span>';if(id==='mcp')html='<span class="small-note">Claude / Cursor + your Salesforce MCP</span>';if(id==='agents')html=`<label>Try a failure <select id="failure"><option value="none">Normal result</option><option value="error">Tool keeps failing</option><option value="missing">Missing order</option></select></label>`;if(id==='evaluation')html=pills([['basic','Basic system'],['checked','With checks']],'variant');if(id==='mcp-lab')html=pills([['demo','Practice tool design'],['real','Try with Claude']],'tab');if(id==='resources')html='<span class="small-note">Read or watch, then mark each resource reviewed.</span>';$('controls').innerHTML=html;$('animation-bar').hidden=['approach','resources'].includes(id);}
function svg(content,label){return `<svg viewBox="0 0 580 330" role="img" aria-label="${escapeHTML(label)}">${content}</svg>`;}
function stages(labels,details,s){return `<div class="stage-cards">${labels.map((x,i)=>`<div class="stage-card ${s===i?'active':''}"><span class="stage-n">0${i+1}</span><strong>${x}</strong><p>${details[i]}</p></div>`).join('')}</div><div class="flow-line"><span class="flow-dot" style="left:${Math.min(s/(labels.length-1)*95,95)}%"></span></div>`;}
function output(label,text){return `<div class="output-card"><div class="output-label">${label}</div>${text}</div>`;}
function render(){const l=lessons[index],id=l.id;let html='',insight='';$('visual').className=`visual ${id==='embeddings'?'map':''}`;$('step-count').textContent=`${step+1} / ${l.steps}`;$('step').disabled=step>=l.steps-1;
 if(id==='embeddings'){
  const chosen=words.find(w=>w[0]===state.word), group=chosen[3];const near=words.filter(w=>w!==chosen).sort((a,b)=>Math.hypot(a[1]-chosen[1],a[2]-chosen[2])-Math.hypot(b[1]-chosen[1],b[2]-chosen[2])).slice(0,3);
  html=svg(`<text x="70" y="32" class="svg-muted">PETS</text><text x="387" y="32" class="svg-muted">MONEY</text><text x="366" y="321" class="svg-muted">TRAVEL</text><ellipse cx="147" cy="126" rx="92" ry="72" fill="#edf5ea"/><ellipse cx="441" cy="87" rx="81" ry="51" fill="#fbf2e7"/><ellipse cx="435" cy="227" rx="90" ry="78" fill="#edf1fa"/>${step>0?near.slice(0,step).map(w=>`<line x1="${chosen[1]}" y1="${chosen[2]}" x2="${w[1]}" y2="${w[2]}" stroke="${colors[group]}" stroke-width="2" stroke-dasharray="4 5"/>`).join(''):''}<circle cx="${chosen[1]}" cy="${chosen[2]}" r="23" fill="${colors[group]}" opacity=".13"/>${words.map(w=>`<g class="map-node" data-word="${w[0]}" tabindex="0" role="button" aria-label="Select ${w[0]}" aria-pressed="${w===chosen}"><circle cx="${w[1]}" cy="${w[2]}" r="${w===chosen?9:6}" fill="${w===chosen?'#123d34':colors[w[3]]}"/><text x="${w[1]+13}" y="${w[2]+5}">${w[0]}</text></g>`).join('')}`,`A teaching map with pets, money, and travel words. ${state.word} is selected.`);
  insight=step===0?`“${state.word}” has a place on our map. Play to find three nearby words.`:`The closest ${step===1?'word is':'words are'} ${near.slice(0,step).map(w=>`“${w[0]}”`).join(', ')}. Search can use distance to find similar ideas.`;
 }
 if(id==='attention'){
  const river=state.sentence==='river',tokens=river?['We','sat','by','the','river','bank']:['She','put','money','in','the','bank'];const weights=river?[5,13,9,3,62,8]:[7,12,61,9,3,8];
  html=`<div class="token-row">${tokens.map(t=>`<span class="token ${t==='bank'?'focused':''}">${t}</span>`).join('')}</div><div class="attention-bars">${tokens.map((t,i)=>`<div class="bar-row"><span>${t}</span><div class="bar-track"><div class="bar-fill" style="width:${step>0?weights[i]:0}%;background:${weights[i]>50?'#43885d':'#b0c9a3'}"></div></div><span class="bar-value">${step>0?weights[i]+'%':'—'}</span></div>`).join('')}</div><p class="diagram-caption">Illustrative weights for “bank” · one simplified attention head</p>`;insight=['First, the model sees small pieces of text called tokens.','“Bank” gives more weight to the useful context words.',`“${river?'River':'Money'}” gives a strong clue. Information from that token helps update “bank”.`,`Here, “bank” means ${river?'the land beside a river':'a place that holds money'}. Attention combines context; it is not a web search.`][step];
 }
 if(id==='context'){
  const n=Number(state.length),pos=Math.round(Number(state.position)/100*(n-1)),middle=1-Math.abs(Number(state.position)-50)/50,short=n===8;
  html=`<div class="output-label">ONE USEFUL FACT IN ${short?'A SHORT':'A LONG'} PROMPT</div><div class="context-strip">${Array.from({length:n},(_,i)=>`<div class="context-block ${i===pos?'fact':''}" style="height:${short?65:45+Math.abs(i-(n-1)/2)*4}px"></div>`).join('')}</div><div class="edge-labels"><span>Start</span><span>Middle</span><span>End</span></div>${output('ILLUSTRATIVE DIFFICULTY',short?'Fewer details compete for attention.':middle>.65?'The fact is in the middle. Some models may struggle to use it.':'The fact is near an edge. Some models use this position better.')}<p class="diagram-caption">Move the fact. This shows a research pattern, not a prediction for any model.</p>`;
  insight=['A fact can fit in the input and still be missed. Move it to explore placement.','Extra text can add noise and distract from the important details.','Put the task clearly, retrieve useful sections, and test facts at different positions.'][step];
 }
 if(id==='training'){
  html=stages(['Pretraining','Fine-tuning','Instruction tuning'],['Lots of broad text. Learn patterns.','Chosen examples. Practice a task or style.','Requests + good answers. Practice following instructions.'],step)+output('A MODEL LEARNS FROM EXAMPLES',['“The sky is ___” → learn which token is likely next.','Example input → target output. Update the learned weights.','“Explain rain simply.” → “Rain is water falling from clouds.”'][step])+'<p class="diagram-caption">Instruction tuning is one kind of fine-tuning.</p>';insight=['Pretraining builds broad patterns in the model’s weights.','Fine-tuning continues training an existing model with a chosen set of examples.','Instruction tuning uses instruction–answer pairs. It is not a required separate step after all fine-tuning.'][step];
 }
 if(id==='prompting'){
  const pieces=[['task','Extract the order ID from: “My order A12 has not arrived.”'],['role','You are a concise customer support helper.'],['example','Example: “Order B34?” → {"order_id":"B34"}'],['format','Return only JSON with one key: order_id.']];
  html=`<div class="prompt-layout"><div><div class="output-label">YOUR PROMPT</div>${pieces.map(([k,t])=>`<div class="prompt-piece ${state[k]?'enabled':''}" style="opacity:${state[k]?1:.4}">${state[k]?escapeHTML(t):'Add '+k+' to include this piece.'}</div>`).join('')}</div><div>${output('FIXED EXAMPLE OUTPUT',!state.task?'What would you like me to do?':state.format?'<pre class="code">{\n  "order_id": "A12"\n}</pre>':'The order ID is A12.')}<p class="small-note">This is a preview of the pattern you ask for. It is not a live response.</p></div></div>`;insight=['A clear task tells the model what to do. Toggle the prompt pieces to compare.','A role guides tone. It does not guarantee knowledge or accuracy.','An example shows the pattern. Include tricky examples as well as easy ones.','An exact format helps your app. Validate the result instead of assuming it will always follow the prompt.'][step];
 }
 if(id==='rag'||id==='rag-lab'){
  if(id==='rag-lab'&&state.tab==='build'){html=output('BUILD IT WITH A FEW PDFs','<ol><li>Choose three PDFs you are allowed to use.</li><li>Extract text and keep the file name and page.</li><li>Split text into small, overlapping pieces.</li><li>Create embeddings and store them in a vector database.</li><li>Embed the question. Retrieve the best pieces.</li><li>Ask a model to answer only from those pieces.</li><li>Show sources. Test questions with no answer.</li></ol>')+'<p class="small-note">For scanned PDFs, use text recognition (OCR). Check tables and page labels after extraction.</p>';insight='Build a small baseline first. Check retrieval separately from the final answer.';}
  else{
   const q=Number(state.question),docs=[['Leave rules.pdf · page 2','Full-time staff get 20 leave days each year.'],['Expenses.pdf · page 1','The meal limit is $30 per person per day.'],['Office access.pdf · page 3','The office opens at 8:00 a.m. on weekdays.']];const labels=id==='rag'?['Question','Find pieces','Build prompt','Answer','Check source']:['Search','Context','Answer','Source check'];const retrieve=step>=1,answered=step>=(id==='rag'?3:2);
   html=`${id==='rag-lab'?'<div class="lab-docs">'+docs.map(d=>`<span class="document-tag">${d[0].split(' · ')[0]}</span>`).join(''):'<div class="step-labels">'+labels.map((n,i)=>`<span class="${i===step?'on':''}">${n}</span>`).join('')+'</div>'}<div class="doc-results">${docs.map((d,i)=>`<div class="doc-result ${retrieve&&q===i?'selected':''}"><span class="score">${retrieve?(q===i?'Best match':q===3?'No answer':'Other topic'):'Not searched'}</span><strong>${d[0]}</strong><p>${retrieve?d[1]:'Text piece waiting to be searched.'}</p></div>`).join('')}</div>${output('ANSWER',answered?(q===3?'I cannot find that answer in these files.':docs[q][1]+` <span class="status">[${docs[q][0]}]</span>`):'Play the steps to see the answer.')}<p class="diagram-caption">Fixed example text · no files leave your browser · no live model</p>`;
   insight=q===3?'No piece contains the CEO’s favorite color. The answer should be “not found”, even if other pieces are retrieved.':(id==='rag'?['Start with a question about your documents.','A vector search finds pieces with related meanings. We highlight the matching sample piece.','Put the retrieved piece and its source in the prompt.','The model writes an answer using that piece.','Check that the cited page really supports the answer.']:['Search the small document library.','The matching piece becomes context for the answer.','Write an answer supported by the piece.','Keep the file name and page next to the claim.'])[step];
  }
 }
 if(id==='approach'){
  const scenarios=[['“Our summaries are too long. We want three short bullets.”','prompt','Start with prompting. Specify three short bullets and show one good example.'],['“Our leave rules change every month. Answers must use the latest document.”','rag','Start with RAG over approved, current documents. Retrieve the right policy and cite it.'],['“We tried prompts, but thousands of replies still miss our exact style. We have good examples.”','tune','Consider fine-tuning for consistent behavior. Split examples into training and test sets. Compare with your best prompt.']];const s=scenarios[Number(state.scenario)];html=`<div class="scenario">${s[0]}</div><div class="choice-buttons">${[['prompt','Prompting'],['rag','RAG'],['tune','Fine-tuning']].map(([v,n])=>`<button class="pill ${state.choice===v?'selected':''}" data-choice="${v}">${n}</button>`).join('')}</div><p class="decision-explain">${state.choice?(state.choice===s[1]?'Good starting point. '+s[2]:'That may be part of a solution. For this case: '+s[2]):'Choose an approach to see the trade-off.'}</p>`;insight='Ask what is missing: clear directions, reliable facts, or repeated behavior. You can combine approaches.';
 }
 if(id==='tools'){
  const logs=['User: “Where is order A12?”','Model request: get_order_status({ order_id: "A12" })','App: validate the ID and check the user’s permission.','Tool result: { order_id: "A12", status: "shipped" }','Model answer: “Order A12 has shipped.”'];html=`<div class="log-lines">${logs.slice(0,step+1).map((x,i)=>`<div class="log-line ${i===step?'active':''}">${escapeHTML(x)}</div>`).join('')}</div>`;insight=['The app gives the model a tool description and its input rules.','The model selects a tool and proposes structured input.','Your code checks the call before executing it.','The tool returns real data. This data is sent back to the model.','The model uses the result to reply. A failed tool needs an honest failure answer.'][step];
 }
 if(id==='mcp'){
  html=stages(['AI app','MCP server','Salesforce'],['Host + client. Discover and request tools.','List tools. Check access. Handle calls.','Use the API to read allowed records.'],Math.min(step,2))+output('MESSAGE ON THE CONNECTION',['1. Client connects to the server. Agree on supported features.','2. Discover tools: find_account and get_opportunity.','3. Call get_opportunity with an allowed opportunity ID.','4. Return the result to the app. The model writes an answer.'][step]);insight=['A host app holds the model and an MCP client. The client connects to your server.','The server exposes tool names, descriptions, and input rules.','The app chooses a call. Your server checks permission and uses the Salesforce API.','The server sends results back. Authentication and least-privilege access still matter.'][step];
 }
 if(id==='agents'){
  const fail=state.failure;let logs=fail==='error'?['Goal: find order A12.','Decide: call get_order_status.','Observe: network error.','Try again once. Observe: network error.','Stop: retry limit reached.','Tell the user: the lookup failed.']:fail==='missing'?['Goal: find order A12.','Decide: call get_order_status.','Observe: order not found.','Decide: ask the user to check the ID.','Stop: more user input is needed.','Tell the user: I could not find A12.']:['Goal: find order A12 and prepare an update.','Decide: look up the order.','Observe: order has shipped.','Decide: draft a short update.','Check: a person must approve sending.','Stop: update is ready for review.'];html=`<div class="step-labels"><span class="${step%3===0?'on':''}">DECIDE</span><span class="${step%3===1?'on':''}">ACT</span><span class="${step%3===2?'on':''}">OBSERVE</span></div><div class="log-lines">${logs.slice(0,step+1).map((x,i)=>`<div class="log-line ${i===step?'active':''}">${x}</div>`).join('')}</div>`;insight=step<4?'The next step depends on the last result. Change the failure mode to compare paths.':fail==='error'?'Stop after the retry limit. Endless retries waste time and money.':fail==='missing'?'Missing data needs user input. Do not invent a record.':'The loop stops at the review boundary. Writing a draft does not mean sending it.';
 }
 if(id==='evaluation'){
  const checked=state.variant==='checked',rows=[['Find a known order','Correct answer','Correct answer'],['Unknown order ID','Invented status','Ask to check ID'],['Private record','Leaked a detail','Access denied'],['Send an update','Sent without review','Wait for approval']];html=`<div class="metrics"><div class="metric"><b>${step===0?'—':checked?`${step===3?4:step} / ${step===3?4:step}`:`1 / ${step===3?4:step}`}</b><span>Cases passed</span></div><div class="metric"><b>${step===0?'—':checked?'1.8 s':'1.2 s'}</b><span>Example latency</span></div><div class="metric"><b>${step===0?'—':checked?'$0.02':'$0.01'}</b><span>Example cost / task</span></div></div><div class="log-lines">${step>0?rows.slice(0,step===3?4:step).map(r=>`<div class="log-line"><strong>${r[0]}</strong>: ${r[checked?2:1]}</div>`).join(''):output('TEST SET','Four cases: a known ID, an unknown ID, a private record, and a write request.')}</div><p class="diagram-caption">Invented teaching results · no claims about a real model or provider</p>`;insight=['Start with a test set and clear pass rules.','Quality, speed, and cost must be measured together.','Input validation and access checks can stop unsafe tool calls.','A human approval step can protect writes. Test the failure cases, not only the happy path.'][step];
 }
 if(id==='mcp-lab'){
  if(state.tab==='real'){html=output('ADD A READ-ONLY TOOL',`<pre class="code">name: get_invoice_status\ninput: { invoice_id: string }\ndescription: Look up invoice status by ID.\nRead only. Does not pay or edit invoices.\n\nhandler:\n  validate invoice_id\n  check user access\n  fetch status from your system\n  return status or a clear error</pre>`)+output('TEST WITH CLAUDE','Connect your MCP server to Claude. Ask each request in the Practice tab at least 10 times. Record the selected tool, inputs, tool result, final answer, cost, and time. Test a missing invoice, denied access, and tool errors too.')+'<p class="small-note">Use a test environment. Keep keys on the server. Count success only when the call and final answer both pass.</p>';insight='A good name and description help selection. Validation and permission checks belong in the server.';}
  else{const good=/status/i.test(state.description)&&/invoice/i.test(state.description)&&/read.only|not pay|does not pay/i.test(state.description);const rows=[['“Status of invoice INV-12?”','get_invoice_status(INV-12)'],['“Check my invoice.”','Ask for an ID'],['“Pay invoice INV-12.”','Do not use this read tool'],['“What is today’s weather?”','Do not use this tool']];html=`<label class="output-label" for="tool-description">TOOL DESCRIPTION</label><textarea id="tool-description" maxlength="600">${escapeHTML(state.description)}</textarea><div class="resource-action"><button class="primary-button" id="test-tool">Run practice tests</button></div>${state.tested?`<table class="test-table"><caption class="sr-only">Illustrative tool selection results</caption><thead><tr><th>REQUEST</th><th>EXPECTED BEHAVIOR</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${r[0]}</td><td>${good?r[1]:i===0?'Unclear description':r[1]}</td></tr>`).join('')}</tbody></table><p class="small-note">${good?'The description states the subject, job, and read-only boundary.':'Try naming the invoice, its status, and the read-only boundary.'} These are fixed rules, not measured Claude results.</p>`:'<p class="small-note">Try a vague description such as “Handle stuff”. Then write a clear one and compare.</p>'}`;insight=['Use an exact tool name and state its purpose.','Define required inputs. Ask the user for missing values.','Include requests that should not use your tool.','Run actual Claude tests many times. Compare tool selection and final answers, not this toy rule score.'][step];}
 }
 if(id==='resources'){
  const rs=[['transformer','3Blue1Brown · Transformers','A visual tour of tokens, embeddings, and model layers.','https://www.3blue1brown.com/lessons/gpt/'],['attention','3Blue1Brown · Attention','See how tokens share context.','https://www.3blue1brown.com/lessons/attention/'],['illustrated','Jay Alammar · The Illustrated Transformer','Read the step-by-step diagrams of the original transformer.','https://jalammar.github.io/illustrated-transformer/'],['prompt','Anthropic · Prompt engineering','Learn clear instructions, examples, and output formats.','https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/overview']];html=rs.map(r=>`<div class="resource-card ${read.has(r[0])?'reviewed':''}"><a target="_blank" rel="noopener noreferrer" href="${r[3]}">${r[1]}</a><p>${r[2]}</p><div class="resource-action"><button class="pill" data-reviewed="${r[0]}" aria-pressed="${read.has(r[0])}">${read.has(r[0])?'✓ Reviewed':'Mark reviewed'}</button></div></div>`).join('');insight=`${read.size} of 4 resources reviewed in this session. After each one, explain an example aloud in simple English.`;
 }
 $('visual').innerHTML=html;$('insight').textContent=insight;syncControls();
}
function syncControls(){document.querySelectorAll('[data-key]').forEach(b=>{const yes=state[b.dataset.key]===b.dataset.value;b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',yes);});if($('word-select'))$('word-select').value=state.word;if($('rag-question'))$('rag-question').value=state.question;if($('scenario'))$('scenario').value=state.scenario;if($('position-value'))$('position-value').textContent=state.position<25?'Near start':state.position>75?'Near end':'Middle';}
function advance(){if(step<lessons[index].steps-1){step++;render();}else stop();}
$('play').onclick=()=>{if(timer){stop();return;}if(step>=lessons[index].steps-1)step=0;$('play').textContent='Pause animation';$('play').setAttribute('aria-pressed','true');render();timer=setInterval(()=>{advance();if(step===lessons[index].steps-1)stop();},1400);};
$('step').onclick=()=>{stop();advance();};$('reset').onclick=()=>{stop();step=0;render();};
$('controls').addEventListener('click',e=>{const b=e.target.closest('[data-key]');if(b)setState(b.dataset.key,b.dataset.value);});
$('controls').addEventListener('change',e=>{if(e.target.dataset.prompt){setState(e.target.dataset.prompt,e.target.checked);return;}const map={'word-select':'word','rag-question':'question','scenario':'scenario','length':'length','failure':'failure'};if(map[e.target.id]){state.choice=null;setState(map[e.target.id],e.target.value);}});
$('controls').addEventListener('input',e=>{if(e.target.id==='position')setState('position',e.target.value);});
$('visual').addEventListener('input',e=>{if(e.target.id==='tool-description'){state.description=e.target.value;state.tested=false;const old=$('test-tool');if(old)old.textContent='Run practice tests';const table=$('visual').querySelector('.test-table');if(table)table.remove();}});
$('visual').addEventListener('click',e=>{const w=e.target.closest('[data-word]');if(w){setState('word',w.dataset.word);return;}const c=e.target.closest('[data-choice]');if(c){state.choice=c.dataset.choice;render();return;}const r=e.target.closest('[data-reviewed]');if(r){read.has(r.dataset.reviewed)?read.delete(r.dataset.reviewed):read.add(r.dataset.reviewed);render();return;}if(e.target.id==='test-tool'){state.tested=true;render();}});
$('visual').addEventListener('keydown',e=>{const w=e.target.closest('[data-word]');if(w&&['Enter',' '].includes(e.key)){e.preventDefault();setState('word',w.dataset.word);}});
$('answers').addEventListener('click',e=>{const b=e.target.closest('[data-answer]');if(!b)return;const l=lessons[index],correct=Number(b.dataset.answer)===l.correct;document.querySelectorAll('.answer').forEach(a=>a.classList.remove('correct','incorrect'));b.classList.add(correct?'correct':'incorrect');$('feedback').textContent=correct?'Yes. '+l.feedback:'Try again. '+l.feedback;});
$('previous').onclick=()=>{if(index>0)location.hash=lessons[index-1].id;};
$('complete').onclick=()=>{completed.add(lessons[index].id);nav();if(index<lessons.length-1){location.hash=lessons[index+1].id;window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}else{$('complete').textContent='Course finished ✓';$('feedback').textContent=completed.size===lessons.length?'All 14 lessons complete. Try explaining one idea to a client.':`You have completed ${completed.size} of 14 lessons. You can go back to finish the others.`;}};
$('menu-button').onclick=()=>{const open=$('sidebar').classList.toggle('open');$('menu-button').setAttribute('aria-expanded',open);$('menu-button').setAttribute('aria-label',open?'Close lesson menu':'Open lesson menu');};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('sidebar').classList.remove('open');$('menu-button').setAttribute('aria-expanded','false');$('menu-button').focus();}});
document.addEventListener('click',e=>{if($('sidebar').classList.contains('open')&&!e.target.closest('#sidebar')&&!e.target.closest('#menu-button')){$('sidebar').classList.remove('open');$('menu-button').setAttribute('aria-expanded','false');}});
window.addEventListener('hashchange',()=>go(location.hash.slice(1)));go(location.hash.slice(1)||'embeddings');
if(document.modelContext?.registerTool){const life=new AbortController();window.addEventListener('pagehide',()=>life.abort(),{once:true});const tools=[{name:'get_learning_state',description:'Read the current lesson, animation step, and session completion count.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({lesson:lessons[index].id,step:step+1,completed:[...completed]})},{name:'open_ai_lesson',description:'Open one visual AI lesson. This navigates the page and resets its animation.',inputSchema:{type:'object',properties:{lesson:{type:'string',enum:lessons.map(l=>l.id)}},required:['lesson'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!lessons.some(l=>l.id===input.lesson))throw new Error('Unknown lesson');history.replaceState(null,'','#'+input.lesson);go(input.lesson);return {lesson:lessons[index].id,step:1};}}];for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}}}
